#! /bin/bash


#-----------------------------

function Func_add() {
# count
number1=$[$(tail -n 1 data/manager.scr/lists | awk '{printf $1}')+1]

# if file is empty
if  cat data/lists | grep -q ^$ ; then
	echo "1 $ENTRY $ENTRY2" > data/manager.scr/lists
	curl -s  "$ENTRY" > data/manager.scr/markers/${number1}.0.marker
else
	echo "$number1 $ENTRY $ENTRY2" >> data/manager.scr/lists
	curl -s  "$ENTRY" > data/manager.scr/markers/${number1}.0.marker
	touch data/manager.scr/filters/${number1}.filter
fi


}
export -f Func_add



GTKDIALOG=gtkdialog

export add='
<window  title="Download source">
<vbox scrollable="true" width-request="600" width="680" height="200">
	<text>
		<label>Add Link:</label>
	</text>
	<entry>
		<variable>ENTRY</variable>
	</entry>

	<text>
		<label>Add Description:</label>
	</text>
	<entry>
		<variable>ENTRY2</variable>
	</entry>
	<hbox>

		<button ok>
				<action>Func_add</action>
				<action>notify-send "Saved all: $CHECKBOX1"</action>
				<variable>addwindow</variable>
				<action type="closewindow">"addwindow"</action>
		</button>

		<button cancel></button>

	</hbox>
</vbox>
</window>
'
gtkdialog -c  --program add



