#! /bin/bash


			RC='\e[0;31m' # Red Color
			NC='\e[0m' # No Color

			funcError()
				{
					# zenity --error --text "$1" ; exit 1
					echo "$1"
					yad --image=dialog-warning \
						--text="<b><span color='red'>$1</span></b>" \
						--button="<b><span color='blue'>OK</span></b>" \
						--title="Error:"
					exit 1
				}


# Check Dependecies
[[ $(echo $SHELL) == "/bin/bash" ]] || { echo -e "${RC} Error: FUUUUUUU  \$SHELL=/bin/bash. ${NC}" ; exit 1 ;}
[[ -z $(which yad) ]] && { echo -e "${RC} Error: FUUUUUUUUU  yad. \n Please install yad. ${NC}" ; exit 1 ;}
[[ -z $(which awk) ]] && funcError " FUUUUUUUUU  awk. \n Please install awk."
[[ -z $(which gtkdialog) ]] && funcError " FUUUUUUUUU  gtkdialog. \n Please install gtkdialog."
[[ -z $(which curl) ]] && funcError " FUUUUUUUUU  curl. \n Please install curl."
[[ -z $(which xdg-open) ]] && funcError " FUUUUUUUUU  xdg-open. \n Please install xdg-open."
[[ -z $(which notify-send) ]] && funcError " FUUUUUUUU  notify-send. \n Please install notify-send."



# Menu in tray icon
echo "-----------------------------"
yad  --title="Test_window" --notification  --listen \
--menu="Check News!data/check_news
Manager!data/manager
Exit !data/kill_yd "Test_window"" \
--separator="\\n" \
 --command='echo Where are the river without water? -On the maps.' --image=data/icons/cool-smilies.png  --button="gtk-close:1"
echo "-----------------------------"


## other options
#CD open!eject
#CD close!eject -t
#Gedit !gedit
#VLC Player !vlc
