#! /bin/bash


PATH_RELATIV=$(dirname "$0")

while IFS= read -r line4 ; do
	link4=$(awk '{print $2}' <<< $line4)
	number4=$(awk '{print $1}' <<< $line4)
	OLD_MARKER="${PATH_RELATIV}/manager.scr/markers/${number4}.0.marker"
	TIME=$(date +"%Y-%m-%d %T")


	if [ -s ${PATH_RELATIV}/manager.scr/filters/${number4}.filter ]; then
		curl -s "$link4" | $(cat ${PATH_RELATIV}/manager.scr/filters/${number4}.filter) > ${PATH_RELATIV}/tmp/${number4}.new.marker
	else
		curl -s "$link4" > ${PATH_RELATIV}/tmp/${number4}.new.marker
	fi


	if cmp -s "$OLD_MARKER" ${PATH_RELATIV}/tmp/${number4}.new.marker ; then
		echo " " >> ${PATH_RELATIV}/logs/fu.log
		echo "$TIME -- Nothing changed" | tee -a ${PATH_RELATIV}/logs/fu.log
		echo "  - $link4" | tee -a ${PATH_RELATIV}/logs/fu.log
	else
		echo " " >> ${PATH_RELATIV}/logs/fu.log
		echo "$TIME -- Something changed" | tee -a ${PATH_RELATIV}/logs/fu.log
		echo "  + $link4" | tee -a ${PATH_RELATIV}/logs/fu.log
		#comm -31 "$OLD_MARKER" ${PATH_RELATIV}/tmp/${number4}.new.marker >> ${PATH_RELATIV}/logs/fu.log
		xdg-open "$link4"
	fi

done < "${PATH_RELATIV}/manager.scr/lists"


